In [1]:
# Import necessary libraries
import scipy.stats as stats
import numpy as np


In [2]:
# Step 1: State the Hypotheses
# Null Hypothesis (H0): There is no significant association between the type of smart home device and customer satisfaction levels.
# Alternate Hypothesis (H1): There is a significant association between the type of smart home device and customer satisfaction levels.


In [3]:
# Step 2: Compute the Chi-Square Statistic
# Observed data (contingency table)
observed = np.array([
    [50, 70],  # Very Satisfied
    [80, 100], # Satisfied
    [60, 90],  # Neutral
    [30, 50],  # Unsatisfied
    [20, 50]   # Very Unsatisfied
])

In [4]:
observed

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

In [5]:
import pandas as pd


In [9]:
import pandas as pd

# Create a DataFrame for the observed data
observed_df = pd.DataFrame(
    observed,
    columns=['Smart Thermostat', 'Smart Light'],
    index=['Very Satisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'Very Unsatisfied']
)

print(observed_df)


                  Smart Thermostat  Smart Light
Very Satisfied                  50           70
Satisfied                       80          100
Neutral                         60           90
Unsatisfied                     30           50
Very Unsatisfied                20           50


In [10]:
# Compute row and column totals
total_rows = observed.sum(axis=1)  # Row totals
total_cols = observed.sum(axis=0)  # Column totals
grand_total = observed.sum()       # Grand total

In [11]:
# Calculate expected frequencies
def calculate_expected(row_total, col_total, grand_total):
    return (row_total * col_total) / grand_total

In [12]:
expected = np.array([[calculate_expected(r, c, grand_total) for c in total_cols] for r in total_rows])

In [13]:
# Compute the Chi-Square Statistic
chi_square_statistic = ((observed - expected)**2 / expected).sum()


In [14]:
# Step 3: Determine the Critical Value
# Degrees of freedom = (number of rows - 1) * (number of columns - 1)
rows, cols = observed.shape
degrees_of_freedom = (rows - 1) * (cols - 1)

In [15]:
# Alpha level (significance level)
alpha = 0.05


In [16]:
# Critical value for the chi-square distribution
critical_value = stats.chi2.ppf(1 - alpha, degrees_of_freedom)

In [17]:
# Step 4: Make a Decision
# Compare the chi-square statistic with the critical value
reject_null = chi_square_statistic > critical_value


In [18]:
# Step 5: Conclusion
if reject_null:
    conclusion = "There is a significant association between the type of smart home device and customer satisfaction levels."
else:
    conclusion = "There is no significant association between the type of smart home device and customer satisfaction levels."


In [19]:
# Print Results
print("Observed Data:")
print(observed)
print("\nExpected Frequencies:")
print(expected)
print("\nChi-Square Statistic:", chi_square_statistic)
print("Degrees of Freedom:", degrees_of_freedom)
print("Critical Value:", critical_value)
print("Decision:", "Reject H0" if reject_null else "Fail to Reject H0")
print("Conclusion:", conclusion)

Observed Data:
[[ 50  70]
 [ 80 100]
 [ 60  90]
 [ 30  50]
 [ 20  50]]

Expected Frequencies:
[[ 48.  72.]
 [ 72. 108.]
 [ 60.  90.]
 [ 32.  48.]
 [ 28.  42.]]

Chi-Square Statistic: 5.638227513227513
Degrees of Freedom: 4
Critical Value: 9.487729036781154
Decision: Fail to Reject H0
Conclusion: There is no significant association between the type of smart home device and customer satisfaction levels.
