In [1]:
pip install scipy

In [2]:
from scipy import stats
import pandas as pd
import numpy as np


In [3]:
# Data: Durability of print-heads (in millions of characters)
data = np.array([1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29])


In [4]:
data

array([1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.2 ,
       1.33, 1.18, 1.22, 1.29])

In [6]:
df=pd.DataFrame(data)

In [7]:
df

0
0   1.13
1   1.55
2   1.43
3   0.92
4   1.25
5   1.36
6   1.32
7   0.85
8   1.07
9   1.48
10  1.20
11  1.33
12  1.18
13  1.22
14  1.29

In [10]:
len(df)

15

In [9]:
t_dis=stats.t.interval(0.99,14,
                             loc = df.mean(),
                             scale = df.std())

In [11]:
print(t_dis)

(array([0.66364743]), array([1.8136859]))


In [12]:
print( 'Mean at 99% confidence interval is:', np.round(t_dis, 4))

Mean at 99% confidence interval is: [[0.6636]
 [1.8137]]


In [13]:
stats.t.ppf(0.99,14)

2.624494067560231

In [14]:
# we have to use t distribution as we dont know sigma for that we a function that is ,stats.t.interval

Build 99% Confidence Interval Using Known Population Standard Deviation

In [15]:
# Population Standard Deviation is known and that is 0.2

In [16]:
df_std = 0.2

In [17]:
#Find confidence interval first using normal distribution
# here stats.norm.interval() will give you directly conf.interval for 95 % confidence. No need to do other calculations.
z_dis = stats.norm.interval(0.99,
loc = df.mean(),
scale = 0.2)
print(z_dis)
print( 'Mean at 99% confidence interval is:', np.round(z_dis, 4))

(array([0.72350081]), array([1.75383253]))
Mean at 99% confidence interval is: [[0.7235]
 [1.7538]]
